config/routes.rb
Pegahome::Application.routes.draw do
  get "pages/home"

  get "pages/pega"

  get "pages/notice"

  get "pages/text_board"

  get "pages/picture_board"

  get "pages/guest_board"

  get "pages/data_board"
  
  root :to => 'pages#home'
  match '/pega',           :to => 'pages#pega'
  match '/notice',         :to => 'pages#notice'
  match '/text_board',     :to => 'pages#text_board'
  match '/picture_board',  :to => 'pages#picture_board'
  match '/guest_board',    :to => 'pages#guest_board'
  match '/data_board',     :to => 'pages#data_board'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def pega
    @title = "Pega IS"
  end

  def notice
    @title = "notice"
  end

  def text_board
    @title = "text_board"
  end

  def picture_board
    @title = "picture_board"
  end

  def guest_board
    @title = "guest_board"
  end

  def data_board
    @title = "data_board"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "PEGASUS Since 1981"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "페가수스란?", pega_path %></li>
			<li><%= link_to "게시판", text_board_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
			<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %> 
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "페가수스란?", pega_path %></li>
			<li><%= link_to "게시판", text_board_path %></li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Sign in", '#' %></li>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if It IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> 
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]--> 
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %> 
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<%= yield %>				
			</section>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/data_board.html.erb
<h1>Pages#data_board</h1>
<p>Find me in app/views/pages/data_board.html.erb</p>

app/views/pages/guest_board.html.erb
<h1>Pages#guest_board</h1>
<p>Find me in app/views/pages/guest_board.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/notice.html.erb
<h1>Pages#notice</h1>
<p>Find me in app/views/pages/notice.html.erb</p>

app/views/pages/pega.html.erb
<h1>Pages#pega</h1>
<p>Find me in app/views/pages/pega.html.erb</p>

app/views/pages/picture_board.html.erb
<h1>Pages#picture_board</h1>
<p>Find me in app/views/pages/picture_board.html.erb</p>

app/views/pages/text_board.html.erb
<h1>Pages#text_board</h1>
<p>Find me in app/views/pages/text_board.html.erb</p>